services:
  auth_db:
    container_name: auth_db
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=accounts
      - POSTGRES_PASSWORD=example
      - POSTGRES_USER=root
      - PORT=9981
    ports:
      - 9981:9981
    command: -p 9981
    networks:
      - book_service_network
  auth_service:
    container_name: auth_service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9980:9980
    depends_on:
      - auth_db
    networks:
      - book_service_network
  keycloak:
    image: 'quay.io/keycloak/keycloak:latest'
    container_name: keycloak
    command: [
       "start-dev","--http-port=9982"]
    ports:
      - 9982:9982
    environment:
      KEYCLOAK_HTTP_PORT: 9982
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://auth_db:9981/accounts
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: example
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - book_service_network
networks:
  book_service_network:
    driver: bridge
    external: true
    name: book_network
